#!/bin/bash
cd /Users/joshuatenbrink/.openclaw/workspace/wildphotography
KEY=$(node scripts/test_api_key.js 2>&1)
echo "Key: $KEY"
echo ""
echo "=== /api/v1/plans ==="
curl -s "https://wildphotography-new.josh-ec6.workers.dev/api/v1/plans" | python3 -c "import sys,json;d=json.load(sys.stdin);print(f'{len(d[\"plans\"])} plans')"
echo ""
echo "=== /api/v1/health ==="
curl -s "https://wildphotography-new.josh-ec6.workers.dev/api/v1/health"
echo ""
echo "=== /api/v1/usage ==="
curl -s "https://wildphotography-new.josh-ec6.workers.dev/api/v1/usage" -H "Authorization: Bearer $KEY"
echo ""
echo "=== /api/v1/search?q=macaw&limit=2 ==="
curl -s "https://wildphotography-new.josh-ec6.workers.dev/api/v1/search?q=macaw&limit=2" -H "Authorization: Bearer $KEY" | python3 -c "import sys,json;d=json.load(sys.stdin);r=d.get('results',[]);print(f'Results: {len(r)}, total: {d.get(\"pagination\",{}).get(\"total\")}')"
echo ""
echo "=== /api/v1/random?count=2 ==="
curl -s "https://wildphotography-new.josh-ec6.workers.dev/api/v1/random?count=2" -H "Authorization: Bearer $KEY" | python3 -c "import sys,json;d=json.load(sys.stdin);print(f'Photos: {len(d.get(\"photos\",[]))}')"
echo ""
echo "=== /api/v1/galleries/costa-rica ==="
curl -s "https://wildphotography-new.josh-ec6.workers.dev/api/v1/galleries/costa-rica" -H "Authorization: Bearer $KEY" | python3 -c "import sys,json;d=json.load(sys.stdin);print(f'Gallery: {d.get(\"gallery\",{}).get(\"name\")}, total: {d.get(\"pagination\",{}).get(\"total\")}')"
echo ""
echo "=== /api/v1/species/keel-billed-toucan ==="
curl -s "https://wildphotography-new.josh-ec6.workers.dev/api/v1/species/keel-billed-toucan" -H "Authorization: Bearer $KEY" | python3 -c "import sys,json;d=json.load(sys.stdin);print(f'Species: {d.get(\"name\")}, photos: {len(d.get(\"photos\",[]))}, related: {len(d.get(\"related_species\",[]))}')"
echo ""
echo "=== /api/v1/locations/puerto-viejo-de-talamanca ==="
curl -s "https://wildphotography-new.josh-ec6.workers.dev/api/v1/locations/puerto-viejo-de-talamanca" -H "Authorization: Bearer $KEY" | python3 -c "import sys,json;d=json.load(sys.stdin);print(f'Location: {d.get(\"name\")}, region: {d.get(\"region\")}, photos: {len(d.get(\"photos\",[]))}')"
echo ""